### ISSUE TITLE
GM attempts auto-send when new repo is added as bi-directional

### ISSUE THREAD

**Issue by tjdurden** [surevine/gateway-management#76]
When adding a new Repo (to receive from a Partner), if you choose 'Bi-directional' federation, the console currently attempts auto-send the repo to that Partner, even though it has not been received (and thus there's nothing to be sent).

**Comment by tjdurden** [comment]
Error message thrown in: /gateway/console/logs/application.log

2015-03-23 15:38:23,944 - [ERROR] - from application in play-akka.actor.default-dispatcher-1081
Failed to distribute repository to partner. Distribution will be reattempted at the next configured federation interval.
com.surevine.gateway.federation.FederatorServiceException: Error response 400 from distribute repository request. CARS:Ford does not exist in the SCM system.
	at com.surevine.gateway.federation.scm.SCMFederatorServiceFacade.distribute(SCMFederatorServiceFacade.java:72) ~[management-console-2.0.1.jar:2.0.1]

**Comment by JonnyHeavey** [comment]
Auto-send functionality has now been disabled - Repo-export will only be attempted at the next federation cycle. UI messages have been modified to better set user expectation.
